name: Approuved-PR WF
run-name: ${{ github.actor }} is using the approuved-pr workflow 🚀
on:
    pull_request_review:
      types: [submitted]
jobs:
    approved:
      if: github.event.review.state == 'approved'
      runs-on: ubuntu-latest
      steps:
        - run: echo "This PR was approved"